version: 2.1

jobs:
  test:
    parameters:
      php-version:
        type: string
        default: "7.4"
    docker:
      - image: cimg/php:<< parameters.php-version >>
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: composer install --no-interaction --prefer-dist --no-suggest
      - run:
          name: Run PHPUnit Tests
          command: vendor/bin/phpunit

workflows:
  version: 2.1
  test:
    jobs:
      - test:
          matrix:
            parameters:
              php-version: ["8.2", "8.4"]